spring.application.name=auth-server
server.port=${SERVER_PORT:9000}
spring.security.oauth2.authorizationserver.issuer=${OAUTH2_ISSUER_URI:http://localhost:9000}

spring.security.oauth2.authorizationserver.client.web.registration.client-id=bff-web
spring.security.oauth2.authorizationserver.client.web.registration.client-secret={noop}${WEB_CLIENT_SECRET:web-secret}
spring.security.oauth2.authorizationserver.client.web.registration.client-authentication-methods[0]=client_secret_basic
spring.security.oauth2.authorizationserver.client.web.registration.authorization-grant-types[0]=client_credentials
spring.security.oauth2.authorizationserver.client.web.registration.scopes[0]=web

spring.security.oauth2.authorizationserver.client.mobile.registration.client-id=bff-mobile
spring.security.oauth2.authorizationserver.client.mobile.registration.client-secret={noop}${MOBILE_CLIENT_SECRET:mobile-secret}
spring.security.oauth2.authorizationserver.client.mobile.registration.client-authentication-methods[0]=client_secret_basic
spring.security.oauth2.authorizationserver.client.mobile.registration.authorization-grant-types[0]=client_credentials
spring.security.oauth2.authorizationserver.client.mobile.registration.scopes[0]=mobile

spring.security.oauth2.authorizationserver.client.atm.registration.client-id=bff-atm
spring.security.oauth2.authorizationserver.client.atm.registration.client-secret={noop}${ATM_CLIENT_SECRET:atm-secret}
spring.security.oauth2.authorizationserver.client.atm.registration.client-authentication-methods[0]=client_secret_basic
spring.security.oauth2.authorizationserver.client.atm.registration.authorization-grant-types[0]=client_credentials
spring.security.oauth2.authorizationserver.client.atm.registration.scopes[0]=atm.read
spring.security.oauth2.authorizationserver.client.atm.registration.scopes[1]=atm.withdraw

spring.security.oauth2.authorizationserver.client.internal.registration.client-id=internal-services
spring.security.oauth2.authorizationserver.client.internal.registration.client-secret={noop}${INTERNAL_CLIENT_SECRET:internal-secret}
spring.security.oauth2.authorizationserver.client.internal.registration.client-authentication-methods[0]=client_secret_basic
spring.security.oauth2.authorizationserver.client.internal.registration.authorization-grant-types[0]=client_credentials
spring.security.oauth2.authorizationserver.client.internal.registration.scopes[0]=internal

management.endpoints.web.exposure.include=health,info
