server.port=${SERVER_PORT:8091}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/customer_db}
spring.datasource.username=${DATABASE_USERNAME:bancoxyz}
spring.datasource.password=${DATABASE_PASSWORD:bancoxyz}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.kafka.consumer.group-id=customer-service
