server.port=${SERVER_PORT:8093}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/payment_db}
spring.datasource.username=${DATABASE_USERNAME:bancoxyz}
spring.datasource.password=${DATABASE_PASSWORD:bancoxyz}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
services.cuentas.url=${CUENTAS_URL:http://account-service}
payment.alerta.monto-minimo=${PAYMENT_ALERT_THRESHOLD:1000000}
resilience4j.circuitbreaker.instances.cuentas.sliding-window-size=10
resilience4j.circuitbreaker.instances.cuentas.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.cuentas.wait-duration-in-open-state=10s
