CREATE TABLE IF NOT EXISTS movimientos_diarios_resultado (
    registro_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file VARCHAR(500) NOT NULL,
    legacy_id BIGINT,
    fecha_original VARCHAR(40),
    fecha DATE,
    monto_original VARCHAR(80),
    monto NUMERIC(19, 2),
    tipo VARCHAR(40),
    estado VARCHAR(20) NOT NULL,
    observacion VARCHAR(500),
    processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS resumen_movimientos_diarios (
    fecha DATE PRIMARY KEY,
    total_registros BIGINT NOT NULL,
    total_debitos BIGINT NOT NULL,
    total_creditos BIGINT NOT NULL,
    total_anomalias BIGINT NOT NULL,
    monto_debitos NUMERIC(19, 2) NOT NULL,
    monto_creditos NUMERIC(19, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS intereses_mensuales_resultado (
    registro_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file VARCHAR(500) NOT NULL,
    cuenta_id BIGINT,
    nombre VARCHAR(200),
    saldo_original VARCHAR(80),
    saldo NUMERIC(19, 2),
    edad_original VARCHAR(40),
    edad INTEGER,
    tipo VARCHAR(40),
    tasa_interes NUMERIC(9, 6),
    interes_calculado NUMERIC(19, 2),
    saldo_final NUMERIC(19, 2),
    estado VARCHAR(20) NOT NULL,
    observacion VARCHAR(500),
    processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS estados_financieros_anuales_resultado (
    registro_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file VARCHAR(500) NOT NULL,
    cuenta_id BIGINT,
    fecha_original VARCHAR(40),
    fecha DATE,
    transaccion VARCHAR(50),
    monto_original VARCHAR(80),
    monto NUMERIC(19, 2),
    descripcion VARCHAR(500),
    estado VARCHAR(20) NOT NULL,
    observacion VARCHAR(500),
    processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS resumen_estados_financieros_anuales (
    cuenta_id BIGINT PRIMARY KEY,
    total_depositos NUMERIC(19, 2) NOT NULL,
    total_retiros NUMERIC(19, 2) NOT NULL,
    total_compras_pagos NUMERIC(19, 2) NOT NULL,
    movimiento_neto NUMERIC(19, 2) NOT NULL,
    cantidad_operaciones BIGINT NOT NULL,
    operaciones_rechazadas BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_movimientos_fecha ON movimientos_diarios_resultado(fecha);
CREATE INDEX IF NOT EXISTS idx_intereses_cuenta ON intereses_mensuales_resultado(cuenta_id);
CREATE INDEX IF NOT EXISTS idx_estados_cuenta ON estados_financieros_anuales_resultado(cuenta_id);
